server:
  port: 8089
  error:
    include-stacktrace: NEVER

spring:
  application:
    name: anime-service
  datasource:
    url: jdbc:mysql://localhost:3306/anime_service?userTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: example
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update