spring:

  profiles:
    active:
     - live
     - test
  application:
    name: service

server:
  port: 8080
  servlet:
    context-path: /
#    context-path: /${spring.application.name}

logging:
  level:
    root: INFO

# D / T / A / P
database:
  url: localhost:5432
  username: ${LOCAL_USERNAME}
  password: ${LOCAL_PASSWORD}

